name: Release

on:
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Dry Release
        id: dry-release
        run:  |
          npx semantic-release --dry-run --no-ci --branches '${HEAD_REF}'
          echo "new-release-version=0.0.6" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
      - name: Use the version
        run: echo "The version is ${{ steps.dry-release.outputs.new-release-version }}"
      - name: Add PR Comment
        uses: thollander/actions-comment-pull-request@9d67388b9a94966eb262e68d9a3b368497990b77
        id: pr-comment
        if: always()
        with:
          message: New version available ${{ steps.dry-release.outputs.new-release-version }}
          comment_tag: execution