name: Release

on:
  push:
    branches:
      - main
      - next
  workflow_call:
  pull-request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Dry Release
        id: dry-release
        run: |
          OUTPUT="$(bash -c "unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci")"
          NEW_RELEASE_VERSION=$(echo "$OUTPUT" | grep -oP 'The next release version is \K(\d+\.\d+\.\d+)')
          echo "new-release-version=$NEW_RELEASE_VERSION" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
      - name: Use the version
        run: echo "The version is null"
      - name: Print PR comment1
        run: echo "The version is ${{ github.ref_name }}"
      - name: Print PR comment2
        run: echo "The version is ${{ github.ref }}"
      - name: Print PR comment3
        run: echo "The version is ${{ steps.dry-release.outputs.new-release-version }}"
      - name: Print PR comment
        run: echo "The version is ${{ github.event_name }}"
      - name: Add PR Comment
        uses: thollander/actions-comment-pull-request@9d67388b9a94966eb262e68d9a3b368497990b77
        if: always()
        with:
          comment_tag: execution
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ${{ steps.dry-release.outputs.new-release-version }}
