name: Release

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Dry Release
        id: dry-release
        run: |
          OUTPUT="$(bash -c "unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci")"
          NEW_RELEASE_VERSION=$(echo "$OUTPUT" | grep -oP 'The next release version is \K(\d+\.\d+\.\d+)')
          echo "new-release-version=$NEW_RELEASE_VERSION" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
      - name: Use the version
        run: echo "The version is ${{ steps.dry-release.outputs.new-release-version }}"
      - name: Add PR Comment
        uses: thollander/actions-comment-pull-request@9d67388b9a94966eb262e68d9a3b368497990b77
        id: pr-comment
        if: always()
        with:
          message: New version available ${{ steps.dry-release.outputs.new-release-version }}
          comment_tag: execution